### PR TITLE
Chetansharma87 stockholm

### PR DESCRIPTION
**Pull request by chetansharma87**
Adding a file that highlight places to eat and drink

### CODE REVIEW

**Comment by chetansharma87** [comment]
please review if the changes looks good.

**Comment by githubteacher** [comment]
@chetansharma87 I have never been to Stockholm, where is the best place to see historical sites and grab some local 🍻 ?

**Comment by chetansharma87** [comment]
@githubteacher start with the capital.

**Comment by alst74** [comment]
Wassup Chetan :smile:

**Pull request merged**
