### PR TITLE
osundblad stockholm

### LINKED ISSUE #14: osundblad's todo list
## Todo
- [x] Create an issue
- [x] Create a branch
- [x] Install Atom
- [ ] Fix Atom uname problem

### PR DESCRIPTION
**Pull request by osundblad**
Added Stockholm highlights 

closes #14

### CODE REVIEW

**Comment by chfisher1978** [comment]
I can't see anything in osundblad-stockholm.md so I'm assuming there is nothing to see or eat?

**Comment by osundblad** [comment]
@chfisher1978 it is there you looked in wrong commit (added text commit)

**Comment by dabeah** [comment]
:scream: :scream: :scream:

**Comment by osundblad** [comment]
@chfisher1978 Made some more changes :shipit: ? Need a :+1:

**Review by chfisher1978 — APPROVED** [review]
👍

**Comment by osundblad** [comment]
closes #14

**Pull request merged**
