### PR TITLE
Add London file

### PR DESCRIPTION
**Pull request by DCPRevere**
Adding the file containing information about what to do in London, UK.

### CODE REVIEW

**Comment by avengerine** [comment]
@DCPRevere any recommendations for drinks?

**Comment by DCPRevere** [comment]
@avengerine The Arbitrager in the City of London is good if you like gin.

**Review by avengerine — COMMENTED** [review]
Please, add that lovely drink place

**Review by avengerine — APPROVED** [review]
:+1:

**Comment by DCPRevere** [comment]
@avengerine I hope this is okay.

**Pull request merged**
