### PR TITLE
Add Dhaka file

### PR DESCRIPTION
**Pull request by ediamin**
Adding the file that highlights places to go in Dhaka.

Closes https://github.com/githubteacher/sep-22-developers/issues/18

### CODE REVIEW

**Comment by ediamin** [comment]
@pszkotak please review this

**Comment by X22** [comment]
@ediamin Is there any places i should visit if I go to Dhaka?

**Comment by ediamin** [comment]
@X22 Of course. My top favourite is our beloved Dhaka University. It has many beautiful places.

**Comment by X22** [comment]
:+1:

**Pull request merged**
