### PR TITLE
Added Stockholm file

### PR DESCRIPTION
**Pull request by katrinsko**
Actually, it's currently all about Södertälje...

### CODE REVIEW

**Comment by chfisher1978** [comment]
Is the beer at Old McLovis good?

**Comment by katrinsko** [comment]
The selection is pretty good for a little town and sometimes they have live music. http://www.mclovis.se/

**Comment by katrinsko** [comment]
@osundblad Added some info on Södertälje, is this ok?

**Comment by osundblad** [comment]
:+1:

**Review by chfisher1978 — APPROVED** [review]
Good stuff 👍

**Pull request merged**
