### PR TITLE
Add Jena file

### PR DESCRIPTION
**Pull request by eckstueck**
Adding file about Jena

Closes https://github.com/githubteacher/sep-22-developers/issues/19

### CODE REVIEW

**Comment by eckstueck** [comment]
@AMill7 Hallo

**Comment by AMill7** [comment]
@eckstueck Nice Work!

**Comment by yagee-de** [comment]
thanks

**Comment by eckstueck** [comment]
@AMill7 :shipit: ? :+1: ?

**Comment by yagee-de** [comment]
👍

**Pull request merged**
